export const LANGUAGES = [
  "Abkhazian", "Afar", "Afrikaans", "Akan", "Albanian", "Amharic", "Arabic",
  "Aragonese", "Armenian", "Assamese", "Avaric", "Avestan", "Aymara",
  "Azerbaijani", "Bambara", "Bashkir", "Basque", "Belarusian", "Bengali",
  "Bislama", "Bosnian", "Breton", "Bulgarian", "Burmese", "Catalan",
  "Chamorro", "Chechen", "Chichewa", "Chinese", "Chuvash", "Cornish",
  "Corsican", "Cree", "Croatian", "Czech", "Danish", "Divehi", "Dutch",
  "Dzongkha", "English", "Esperanto", "Estonian", "Ewe", "Faroese", "Fijian",
  "Finnish", "French", "Fula", "Galician", "Georgian", "German", "Greek",
  "Guaraní", "Gujarati", "Haitian Creole", "Hausa", "Hebrew", "Herero",
  "Hindi", "Hiri Motu", "Hungarian", "Interlingua", "Indonesian", "Interlingue",
  "Irish", "Igbo", "Inupiaq", "Ido", "Icelandic", "Italian", "Inuktitut",
  "Japanese", "Javanese", "Kalaallisut", "Kannada", "Kanuri", "Kashmiri",
  "Kazakh", "Khmer", "Kikuyu", "Kinyarwanda", "Kyrgyz", "Komi", "Kongo",
  "Korean", "Kurdish", "Kwanyama", "Latin", "Luxembourgish", "Luganda",
  "Limburgish", "Lingala", "Lao", "Lithuanian", "Luba-Katanga", "Latvian",
  "Manx", "Macedonian", "Malagasy", "Malay", "Malayalam", "Maltese", "Māori",
  "Marathi", "Marshallese", "Mongolian", "Nauru", "Navajo", "Norwegian Bokmål",
  "North Ndebele", "Nepali", "Ndonga", "Norwegian Nynorsk", "Norwegian",
  "Nuosu", "South Ndebele", "Occitan", "Ojibwe", "Old Church Slavonic",
  "Oromo", "Oriya", "Ossetian", "Panjabi", "Pali", "Persian", "Polish",
  "Pashto", "Portuguese", "Quechua", "Romansh", "Kirundi", "Romanian",
  "Russian", "Sanskrit", "Sardinian", "Sindhi", "Northern Sami", "Samoan",
  "Sango", "Serbian", "Scottish Gaelic", "Shona", "Sinhala", "Slovak",
  "Slovenian", "Somali", "Southern Sotho", "Spanish", "Sundanese", "Swahili",
  "Swati", "Swedish", "Tamil", "Telugu", "Tajik", "Thai", "Tigrinya",
  "Tibetan", "Turkmen", "Tagalog", "Tswana", "Tonga", "Turkish", "Tsonga",
  "Tatar", "Twi", "Tahitian", "Uyghur", "Ukrainian", "Urdu", "Uzbek",
  "Venda", "Vietnamese", "Volapük", "Walloon", "Welsh", "Wolof", "Western Frisian",
  "Xhosa", "Yiddish", "Yoruba", "Zhuang", "Zulu",
];
